version: "3.9"

services:
  web:
    build: .
    container_name: elsewhere_web
    restart: unless-stopped

    ports:
      - "5042:5000"

    environment:
      FLASK_ENV: production
      FLASK_SECRET_KEY: "replace-this-with-a-long-random-string"
      ADMIN_PASSWORD: "replace-this-with-a-strong-password"

    volumes:
      - instance_data:/app/instance

volumes:
  instance_data:
